In [1]:
from typing import List, Dict
import requests
import pandas as pd

In [2]:
state_fips = {
            'ALABAMA': '01',
            'ALASKA': '02',
            'ARIZONA': '04',
            'ARKANSAS': '05',
            'CALIFORNIA': '06',
            'COLORADO': '08',
            'CONNECTICUT': '09',
            'DELAWARE': '10',
            'DISTRICT OF COLUMBIA': '11',
            'FLORIDA': '12',
            'GEORGIA': '13',
            'HAWAII': '15',
            'IDAHO': '16',
            'ILLINOIS': '17',
            'INDIANA': '18',
            'IOWA': '19',
            'KANSAS': '20',
            'KENTUCKY': '21',
            'LOUISIANA': '22',
            'MAINE': '23',
            'MARYLAND': '24',
            'MASSACHUSETTS': '25',
            'MICHIGAN': '26',
            'MINNESOTA': '27',
            'MISSISSIPPI': '28',
            'MISSOURI': '29',
            'MONTANA': '30',
            'NEBRASKA': '31',
            'NEVADA': '32',
            'NEW HAMPSHIRE': '33',
            'NEW JERSEY': '34',
            'NEW MEXICO': '35',
            'NEW YORK': '36',
            'NORTH CAROLINA': '37',
            'NORTH DAKOTA': '38',
            'OHIO': '39',
            'OKLAHOMA': '40',
            'OREGON': '41',
            'PENNSYLVANIA': '42',
            'RHODE ISLAND': '44',
            'SOUTH CAROLINA': '45',
            'SOUTH DAKOTA': '46',
            'TENNESSEE': '47',
            'TEXAS': '48',
            'UTAH': '49',
            'VERMONT': '50',
            'VIRGINIA': '51',
            'WASHINGTON': '53',
            'WEST VIRGINIA': '54',
            'WISCONSIN': '55',
            'WYOMING': '56',
            'PUERTO RICO': '72'
        }

In [3]:
class CensusDataRetriever:
    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://api.census.gov/data"
        self.year = "2022"  # Most recent ACS 5-year estimates
        self.dataset = "acs/acs5"
        
    def get_variable_groups(self) -> Dict:
        """Retrieve available variable groups for reference"""
        url = f"{self.base_url}/{self.year}/{self.dataset}/groups.json"
        response = requests.get(url)
        return response.json()
    
    def get_place_data(self, state_fips: str, variables: List[str]) -> pd.DataFrame:
        """
        Retrieve data for all places (cities) in a state
        
        Parameters:
        state_fips: Two-digit state FIPS code
        variables: List of Census variable codes
        """
        # Construct variable string
        var_str = ",".join(variables)
        
        # Build API URL
        url = f"{self.base_url}/{self.year}/{self.dataset}"
        
        # Parameters for the request
        params = {
            "get": f"NAME,{var_str}",
            "for": "place:*",
            "in": f"state:{state_fips}",
            "key": self.api_key
        }
        
        response = requests.get(url, params=params)
        if response.status_code != 200:
            raise Exception(f"API request failed: {response.text}")
            
        # Convert response to DataFrame
        data = response.json()
        df = pd.DataFrame(data[1:], columns=data[0])
        return df

In [50]:
class CensusDataRetriever:
    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://api.census.gov/data"
        self.year = "2022"  # Most recent ACS 5-year estimates
        self.dataset = "acs/acs5"
        
    def get_variable_groups(self) -> Dict:
        """Retrieve available variable groups for reference"""
        url = f"{self.base_url}/{self.year}/{self.dataset}/groups.json"
        response = requests.get(url)
        return response.json()
    
    def get_metro_data(self, variables: List[str]) -> pd.DataFrame:
        """
        Retrieve data for all Metropolitan Statistical Areas (CBSAs)
        
        Parameters:
        variables: List of Census variable codes
        """
        # Construct variable string
        var_str = ",".join(variables)
        
        # Build API URL
        url = f"{self.base_url}/{self.year}/{self.dataset}"
        
        # Parameters for the request - using CBSA (Core Based Statistical Area) geography
        params = {
            "get": f"NAME,{var_str}",
            "for": "metropolitan statistical area/micropolitan statistical area:*",
            "key": self.api_key
        }
        
        response = requests.get(url, params=params)
        if response.status_code != 200:
            raise Exception(f"API request failed: {response.text}")
            
        # Convert response to DataFrame
        data = response.json()
        df = pd.DataFrame(data[1:], columns=data[0])
        
        # Filter to only metropolitan areas (population >= 50,000)
        # Convert population to numeric for filtering
        df['B01001_001E'] = pd.to_numeric(df['B01001_001E'])
        metro_areas = df[df['B01001_001E'] >= 50000].copy()
        
        return metro_areas
    
    def get_component_places(self, cbsa_code: str, variables: List[str]) -> pd.DataFrame:
        """
        Get all places (cities) within a specific CBSA
        
        Parameters:
        cbsa_code: The CBSA code for the metropolitan area
        variables: List of Census variable codes
        """
        var_str = ",".join(variables)
        url = f"{self.base_url}/{self.year}/{self.dataset}"
        
        params = {
            "get": f"NAME,{var_str}",
            "for": "place:*",
            "in": f"metropolitan statistical area/micropolitan statistical area:{cbsa_code}",
            "key": self.api_key
        }
        
        response = requests.get(url, params=params)
        if response.status_code != 200:
            raise Exception(f"API request failed: {response.text}")
            
        data = response.json()
        return pd.DataFrame(data[1:], columns=data[0])

In [51]:
API_KEY = "185f22854b5fff8e12d4d135d81adabd7ede4310"
    
  # Initialize retriever
retriever = CensusDataRetriever(API_KEY)

# Example variables for different demographics
# You can find more variables at: https://api.census.gov/data/2022/acs/acs5/variables.html


column_map = {
        'B01001_001E': 'total_population',
        'B01001H_025E': 'female_white_30_34',
        'B01001D_025E': 'female_asian_30_34',
        'B01001D_010E': 'male_asian_30_34',
        'B01001H_010E': 'male_white_30_34',
        'B01001H_011E': 'male_white_35_39',
        'B01001D_011E': 'male_asian_35_39',
        'B01001_036E': 'female_total_30_34',
        'B01001_012E': 'male_total_30_34',
        'B01001_013E': 'male_total_35_39',
        

        'B12002_101E': 'female_never_married_30_34',
        'B12002_102E': 'female_never_married_35_39',
        'B12002_008E': 'male_never_married_30_34',
        'B12002_009E': 'male_never_married_35_39',
}

variables = [k for k, v in column_map.items()]

In [32]:
ca_data = retriever.get_place_data("06", variables)
ca_data = ca_data.rename(columns=column_map)
num_cols = list(column_map.values())
ca_data[num_cols] = ca_data[num_cols].apply(pd.to_numeric)

In [54]:
metro_data = retriever.get_metro_data(variables)
metro_data = metro_data.rename(columns=column_map)
num_cols = list(column_map.values())
metro_data[num_cols] = metro_data[num_cols].apply(pd.to_numeric)

In [55]:
metro_data.head()

,NAME,total_population,female_white_30_34,female_asian_30_34,male_asian_30_34,male_white_30_34,male_white_35_39,male_asian_35_39,female_total_30_34,male_total_30_34,male_total_35_39,female_never_married_30_34,female_never_married_35_39,male_never_married_30_34,male_never_married_35_39,metropolitan statistical area/micropolitan statistical area
1,"Aberdeen, WA Micro Area",75672,1553,33,31,1793,3596,97,1982,2494,2396,704,618,1238,883,10140
2,"Abilene, TX Metro Area",176656,3395,132,129,3617,6642,226,5683,6575,6339,1406,935,2641,1816,10180
4,"Adrian, MI Micro Area",99263,2266,0,3,2429,5154,7,2666,2932,3401,794,668,1322,1027,10300
5,"Aguadilla-Isabela, PR Metro Area",308919,535,16,0,335,311,20,9099,8927,7757,5504,3238,6179,4327,10380
6,"Akron, OH Metro Area",700578,16223,1052,1047,17040,32135,1967,21930,22021,20956,8727,4961,10659,6951,10420

In [56]:
populous = (metro_data[(metro_data["female_asian_30_34"] > 500) &
            (metro_data["female_never_married_30_34"] > 500)]).copy()

In [1]:
def favorable_dating_index(df):
    fdi = ((df["female_asian_30_34"] + df["female_white_30_34"])* (df["female_never_married_30_34"] / df["female_total_30_34"])
           / (((df["male_never_married_30_34"] + df["male_never_married_35_39"]) / (df["male_total_30_34"] + df["male_total_35_39"]))
              * (df["male_white_30_34"] + df["male_white_35_39"] + df["male_asian_30_34"] + df["male_asian_35_39"])))
    return fdi

In [2]:
populous["fdi"] = favorable_dating_index(populous)
populous["f_to_m"] = populous["female_never_married_30_34"] / populous["male_never_married_30_34"]
populous["f_surplus"] = populous["female_never_married_30_34"] - populous["male_never_married_30_34"]

NameError: name 'populous' is not defined

In [60]:
len(populous)

124

In [59]:
populous.sort_values(by='fdi', ascending=False).head(20)

,NAME,total_population,female_white_30_34,female_asian_30_34,male_asian_30_34,male_white_30_34,male_white_35_39,male_asian_35_39,female_total_30_34,male_total_30_34,male_total_35_39,female_never_married_30_34,female_never_married_35_39,male_never_married_30_34,male_never_married_35_39,metropolitan statistical area/micropolitan statistical area,fdi,f_to_m,f_surplus
434,"Kapaa, HI Micro Area",73511,654,730,505,578,1419,1166,2225,2200,2518,1239,830,1241,1061,28180,0.227137,0.998388,-2
868,"Urban Honolulu, HI Metro Area",1010100,6860,12746,11449,8670,14526,24354,34667,38550,36251,13477,9305,19297,12642,46520,0.196695,0.698399,-5820
759,"San Jose-Sunnyvale-Santa Clara, CA Metro Area",1981584,17584,33853,38438,22041,39708,62150,74289,87149,79406,26066,14616,42495,23836,41940,0.183726,0.613390,-16429
757,"San Francisco-Oakland-Berkeley, CA Metro Area",4692242,62773,59750,56408,71307,129367,101334,187300,198762,190045,84132,51157,110274,69901,41860,0.161590,0.762936,-26142
377,"Hilo, HI Micro Area",202163,1501,1168,1032,1473,3529,2432,6191,5974,6551,3357,2025,3945,2568,25900,0.143864,0.850951,-588
825,"Stockton, CA Metro Area",779445,6675,5114,5065,7104,14079,9780,26377,27470,28216,10700,7030,14049,9424,44700,0.136602,0.761620,-3349
429,"Kahului-Wailuku-Lahaina, HI Metro Area",164765,1521,1227,1032,1420,3439,2836,5241,5004,6147,2200,1844,2849,2171,27980,0.131099,0.772201,-649
499,"Los Angeles-Long Beach-Anaheim, CA Metro Area",13111917,134243,84179,79849,147736,258624,145281,493667,521972,476114,245914,149857,316446,196928,31080,0.129098,0.777112,-70532
314,"Fresno, CA Metro Area",1008280,8996,5204,5260,9251,17670,7572,36553,38683,36190,14813,9501,18634,13349,23420,0.124192,0.794945,-3821
608,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",19908595,284998,103291,95058,292612,527611,179360,720294,728359,681003,343704,208810,410308,245362,35620,0.096784,0.837673,-66604
872,"Vallejo, CA Metro Area",450995,5233,2428,2260,5740,10402,4418,15926,16942,16085,6019,3981,8184,5851,46700,0.094625,0.735459,-2165
736,"Sacramento-Roseville-Folsom, CA Metro Area",2394673,38034,14844,13336,39084,77148,23846,84811,86727,84970,32539,19884,42413,27494,40900,0.091176,0.767194,-9874
545,"Merced, CA Metro Area",282290,2233,819,992,2345,4314,1341,9472,10587,9866,3787,2557,5000,3589,32900,0.086715,0.757400,-1213
775,"Seattle-Tacoma-Bellevue, WA Metro Area",4001701,91891,33339,33615,100844,181751,51981,166511,181272,165845,60390,34018,86654,50657,42660,0.083018,0.696910,-26264
753,"San Diego-Chula Vista-Carlsbad, CA Metro Area",3289701,51161,18322,17549,57338,101711,29388,126889,138865,124361,49213,27685,71080,40917,41740,0.081080,0.692361,-21867
896,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",6346083,99832,28141,24944,101277,193679,53617,235299,233225,239576,98724,65686,117492,72422,47900,0.078696,0.840261,-18768
388,"Houston-The Woodlands-Sugar Land, TX Metro Area",7142603,81667,24575,21722,84249,166983,44799,262926,265333,266336,91056,60923,116987,74495,26420,0.074369,0.778343,-25931
716,"Riverside-San Bernardino-Ontario, CA Metro Area",4610050,40032,12201,11402,42130,82369,21642,160515,169261,157783,63187,36272,85415,49154,40140,0.074092,0.739765,-22228
935,"Yuba City, CA Metro Area",180806,2920,958,873,2974,5297,1475,6512,6711,6775,1876,1783,2750,2017,49700,0.073526,0.682182,-874
854,"Trenton-Princeton, NJ Metro Area",383732,4696,1486,1370,4872,9712,4026,11440,12007,12524,5113,3568,6721,4376,45940,0.073482,0.760750,-1608

In [63]:
populous.sort_values(by='f_to_m', ascending=False).head(50)

,NAME,total_population,female_white_30_34,female_asian_30_34,male_asian_30_34,male_white_30_34,male_white_35_39,male_asian_35_39,female_total_30_34,male_total_30_34,male_total_35_39,female_never_married_30_34,female_never_married_35_39,male_never_married_30_34,male_never_married_35_39,metropolitan statistical area/micropolitan statistical area,fdi,f_to_m,f_surplus
543,"Memphis, TN-MS-AR Metro Area",1335804,17773,1370,1120,17612,34597,2682,47873,44018,40927,23360,17054,22486,13964,32820,0.027814,1.038869,874
603,"New Orleans-Metairie, LA Metro Area",1264357,22271,1657,1242,21752,42598,2492,47762,43663,44721,25636,17366,25559,17791,35380,0.026634,1.003013,77
434,"Kapaa, HI Micro Area",73511,654,730,505,578,1419,1166,2225,2200,2518,1239,830,1241,1061,28180,0.227137,0.998388,-2
345,"Greensboro-High Point, NC Metro Area",775169,12823,1334,1223,12339,23916,2458,25860,23226,22466,11199,6428,11435,7255,24660,0.035365,0.979362,-236
491,"Little Rock-North Little Rock-Conway, AR Metro...",749290,16279,804,356,16126,31463,1147,26729,24751,25412,9810,6731,10118,7156,30780,0.017455,0.969559,-308
90,"Birmingham-Hoover, AL Metro Area",1114368,22123,913,702,21594,42794,1318,38952,36549,34373,15058,9063,15931,9210,13820,0.014993,0.945201,-873
47,"Atlanta-Sandy Springs-Alpharetta, GA Metro Area",6094752,88714,17250,15623,88610,174388,33665,221065,208397,209499,92900,62119,98612,65185,12060,0.059224,0.942076,-5712
406,"Jackson, MS Metro Area",591397,8283,524,272,8000,17152,792,20246,19390,19257,8578,6527,9222,6828,27140,0.020392,0.930167,-644
185,"Columbia, SC Metro Area",831913,14469,846,728,14295,27463,1385,28529,26670,25370,11915,7892,12835,7245,17900,0.020872,0.928321,-920
158,"Charleston-North Charleston, SC Metro Area",803398,20195,614,653,19748,36216,1155,31667,30525,29727,12408,7842,13371,9178,16700,0.011127,0.927978,-963
246,"Durham-Chapel Hill, NC Metro Area",648066,13052,1502,1589,12579,22078,2294,24079,23663,21267,10644,6576,11550,7259,20500,0.041152,0.921558,-906
220,"Dayton-Kettering, OH Metro Area",812506,19446,763,832,19841,36595,1504,26563,26780,24563,10885,6172,11903,7919,19430,0.013780,0.914475,-1018
444,"Killeen-Temple, TX Metro Area",477577,8131,530,539,8039,14379,707,18510,18642,17321,5950,3797,6556,4259,28660,0.023940,0.907566,-606
59,"Baltimore-Columbia-Towson, MD Metro Area",2840005,53163,7248,6084,53748,97070,13781,105358,100417,97405,47142,31108,52005,31758,12580,0.044874,0.906490,-4863
68,"Baton Rouge, LA Metro Area",869755,15148,778,812,15491,31093,1483,28997,29711,30247,12689,9975,14116,10147,12940,0.017212,0.898909,-1427
665,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",6232894,124295,18047,16678,127442,232252,31434,224640,221470,204020,104129,66035,115947,71310,37980,0.046611,0.898074,-11818
464,"Lancaster, PA Metro Area",553202,13863,617,466,13895,24896,897,18066,18011,16317,5759,3591,6429,3691,29540,0.016615,0.895785,-670
400,"Indianapolis-Carmel-Anderson, IN Metro Area",2109957,50859,4082,3358,50533,97922,7926,76186,74576,74536,28074,17191,31816,18934,26900,0.027667,0.882386,-3742
173,"Cleveland-Elyria, OH Metro Area",2079759,42145,2461,2226,44025,84694,4395,67136,66288,62631,30964,21454,35147,23253,17460,0.018514,0.880986,-4183
713,"Richmond, VA Metro Area",1316145,25531,2606,2568,25381,47633,5175,48272,47295,45919,21203,12794,24156,15275,40060,0.033507,0.877753,-2953
602,"New Haven-Milford, CT Metro Area",866377,14285,1650,1485,14507,28105,2503,28502,27914,25390,14028,9184,15991,9554,35300,0.036364,0.877243,-1963
595,"Nashville-Davidson--Murfreesboro--Franklin, TN...",1990873,53239,3099,2528,52542,96250,5610,77183,74719,71731,26798,17765,30574,20186,34980,0.019782,0.876496,-3776
742,"St. Louis, MO-IL Metro Area",2813523,65446,3573,3856,66358,133209,6799,95853,93443,94282,36587,23688,42312,29073,41180,0.017060,0.864696,-5725
812,"Springfield, MA Metro Area",689486,13282,636,561,13279,25937,929,21143,21553,19413,10210,7245,11887,8461,44140,0.015190,0.858922,-1677
377,"Hilo, HI Micro Area",202163,1501,1168,1032,1473,3529,2432,6191,5974,6551,3357,2025,3945,2568,25900,0.143864,0.850951,-588
350,"Greenville-Anderson, SC Metro Area",931405,20983,586,761,20716,39297,1353,30525,29870,28426,10154,8008,11978,7876,24860,0.009213,0.847721,-1824
883,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",1798025,33301,3074,2542,35848,62972,5032,66396,66927,61241,23957,15316,28294,16993,47260,0.029504,0.846717,-4337
722,"Rochester, NY Metro Area",1086859,25018,1394,1236,25763,47336,2069,35728,36062,32747,16167,10718,19101,11354,40380,0.018653,0.846395,-2934
125,"Buffalo-Cheektowaga, NY Metro Area",1163462,28695,2083,1629,30168,52159,3034,40076,40576,36686,18173,10985,21540,12844,15380,0.024399,0.843686,-3367
159,"Charlotte-Concord-Gastonia, NC-SC Metro Area",2668688,52954,5754,5666,52748,102145,12025,96560,93061,90467,36718,23822,43623,26694,16740,0.033090,0.841712,-6905
896,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",6346083,99832,28141,24944,101277,193679,53617,235299,233225,239576,98724,65686,117492,72422,47900,0.078696,0.840261,-18768
834,"Syracuse, NY Metro Area",658694,16023,852,758,16604,30634,1130,21116,20876,19721,9207,6008,10962,6471,45060,0.017610,0.839901,-1755
105,"Boston-Cambridge-Newton, MA-NH Metro Area",4912449,112387,21392,19937,114371,198043,33785,180852,183118,167030,80782,47296,96287,50935,14460,0.062070,0.838971,-15505
608,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",19908595,284998,103291,95058,292612,527611,179360,720294,728359,681003,343704,208810,410308,245362,35620,0.096784,0.837673,-66604
555,"Milwaukee-Waukesha, WI Metro Area",1568940,32118,3228,3342,33655,66273,5633,54036,53494,52113,23614,16510,28282,18407,33340,0.029299,0.834948,-4668
564,"Modesto, CA Metro Area",552063,6880,1466,1411,7089,13297,2367,19372,20079,18970,7775,4423,9323,6215,33700,0.061194,0.833959,-1548
500,"Louisville/Jefferson County, KY-IN Metro Area",1282588,31056,1413,1362,31436,61243,2513,43686,44038,42166,16629,10330,20069,13819,31140,0.014170,0.828591,-3440
163,"Chicago-Naperville-Elgin, IL-IN-WI Metro Area",9566955,161131,29679,28795,168858,323791,55031,333667,340086,336316,145962,96921,177347,114230,16980,0.052245,0.823031,-31385
703,"Raleigh-Cary, NC Metro Area",1420825,30123,4317,3592,30233,58960,10271,52391,50585,51510,17434,11258,21287,13294,39580,0.041154,0.818998,-3853
6,"Akron, OH Metro Area",700578,16223,1052,1047,17040,32135,1967,21930,22021,20956,8727,4961,10659,6951,10420,0.019577,0.818745,-1932
838,"Tampa-St. Petersburg-Clearwater, FL Metro Area",3194310,57425,5100,4591,57098,109393,9536,107230,106346,103814,43996,29865,53825,35295,45300,0.027320,0.817390,-9829
212,"Dallas-Fort Worth-Arlington, TX Metro Area",7673379,114742,26955,24981,115403,226244,54319,285000,283463,274450,95882,61153,117553,68332,19100,0.064659,0.815649,-21671
692,"Poughkeepsie-Newburgh-Middletown, NY Metro Area",697704,11854,604,553,12293,24390,1432,19927,21271,20237,8253,4438,10152,6250,39100,0.016372,0.812943,-1899
768,"Savannah, GA Metro Area",406575,8201,586,363,8172,15030,719,15472,15235,13601,5461,3586,6718,4173,42340,0.022551,0.812891,-1257
629,"Omaha-Council Bluffs, NE-IA Metro Area",966688,24251,1750,1748,25069,50180,2823,33859,34560,35106,10902,7360,13463,9649,36540,0.021279,0.809775,-2561
182,"College Station-Bryan, TX Metro Area",269418,4199,548,710,4419,7640,1241,8785,9023,8755,2989,1613,3701,2445,17780,0.038496,0.807620,-712
465,"Lansing-East Lansing, MI Metro Area",538985,12582,875,907,12857,24417,1558,16701,17182,16540,6498,4029,8049,4417,29620,0.023175,0.807305,-1551
166,"Cincinnati, OH-KY-IN Metro Area",2253528,55756,3150,3118,56854,110505,5589,74578,75168,74819,27136,17141,33893,22183,17140,0.017412,0.800637,-6757
696,"Providence-Warwick, RI-MA Metro Area",1670949,38556,2669,2443,39289,70852,4360,56385,57907,54210,25715,16324,32138,19977,39300,0.022392,0.800143,-6423
752,"San Antonio-New Braunfels, TX Metro Area",2570862,27327,3526,2949,29166,54725,5933,93202,97897,94643,34044,22724,42685,29118,41700,0.037227,0.797564,-8641